openapi: 3.0.3
info:
  title: Payment Service API
  version: 1.0.0
  description: API сервиса платежей для интеграции с витриной интернет-магазина

paths:
  /balance/{userId}:
    get:
      summary: Получить баланс пользователя
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: Идентификатор пользователя
      responses:
        '200':
          description: Баланс пользователя успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '404':
          description: Пользователь не найден

  /payment:
    post:
      summary: Совершить платеж
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: Платеж успешно совершен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Ошибка оплаты (недостаточно средств или другие ошибки)

components:
  schemas:
    BalanceResponse:
      type: object
      properties:
        userId:
          type: string
          example: user123
        balance:
          type: number
          format: double
          example: 1500.75

    PaymentRequest:
      type: object
      required:
        - userId
        - amount
      properties:
        userId:
          type: string
          example: user123
        amount:
          type: number
          format: double
          example: 250.00

    PaymentResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Платеж прошел успешно"
