version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=onlinestore
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5430:5432"
  app:
    build: ./shop-service
    ports:
      - "3333:8080"
    depends_on:
      - db
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/mydatabase
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=onlinestore
      - SPRING_REDIS_HOST=localhost
      - SPRING_REDIS_PORT=6379
      - PAYMENT_API_URL=http://payment-service:8081
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8081"

volumes:
  pgdata:
  redis_data:


