#version: '3.8'
#services:
#  db:
#    image: postgres:latest
#    container_name: my-postgres
#    environment:
#      - POSTGRES_DB=mydatabase
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=onlinestore
#    volumes:
#      - pgdata:/var/lib/postgresql/data/
#    ports:
#      - "5430:5432"
#  app:
#    build: ./shop-service
#    ports:
#      - "3333:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/mydatabase
#      - SPRING_R2DBC_USERNAME=user
#      - SPRING_R2DBC_PASSWORD=onlinestore
#      - SPRING_REDIS_HOST=localhost
#      - SPRING_REDIS_PORT=6379
#      - PAYMENT_API_URL=http://payment-service:8081
#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6378:6379"
#    volumes:
#      - redis_data:/data
#    command: redis-server --appendonly yes
#
#  payment-service:
#    build: ./payment-service
#    container_name: payment-service
#    ports:
#      - "8081:8081"
#
#volumes:
#  pgdata:
#  redis_data:
#
#

version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=onlinestore
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5430:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloakk
    command: start-dev
    ports:
      - "8082:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-data:/opt/keycloak/data

  shop-service:
    build: ./shop-service
    ports:
      - "3333:8085"
    depends_on:
      - db
      - redis
      - keycloak
      - payment-service
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/mydatabase
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=onlinestore
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - PAYMENT_API_URL=http://payment-service:8081
      - KEYCLOAK_URL=http://keycloak:8080
      - SERVER_PORT=8085

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/mydatabase
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=onlinestore
      - KEYCLOAK_URL=http://keycloak:8080

volumes:
  pgdata:
  redis_data:
