openapi: 3.0.3
info:
  title: Payment Service API
  version: 1.0.0
  description: API сервиса платежей

paths:
  /balance:
    get:
      summary: Получить текущий баланс
      responses:
        '200':
          description: Баланс успешно получен
          content:
            application/json:
              schema:
                type: number
                format: double
                example: 1500.75

  /payment:
    post:
      summary: Совершить платёж
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: Платёж успешно выполнен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Ошибка при выполнении платежа

components:
  schemas:
    PaymentRequest:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
          format: double
          example: 250.00

    PaymentResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Платёж прошёл успешно"
